### ISSUE TITLE
Power cycle needed after failed to detect SD card.

### ISSUE THREAD

**Issue by aschulm** [aschulm/battor#26]
LEDs should blink in a special way to notify that the SD card has failed. Right now if the card can not be read from the driver just halts.

**Comment by testaco** [comment]
It'd be nice too if it set the error code as well.

**Comment by aschulm** [comment]
we just need to put a check around sd_init() in drivers.c to halt if a negative value is returned

**Comment by aschulm** [comment]
CC @zeptonaut, @randalnephew, @nedn. This seems to be the firmware bug that lead to the halt in https://crbug.com/732532
