### ISSUE TITLE
Feature request: command-line option to change sampling rate

### ISSUE THREAD

**Issue by peastham** [aschulm/battor#32]
Need an option to sample at a much lower rate --  very hard to download/work with 10KHz data if your run is an hour or longer.

In many cases 1Hz is sufficient for what I do, but 5 or 10 is typical.

**Comment by aschulm** [comment]
This should be sufficiently fixed in 73f8ae6529b819db974cf60a43674efc983f1886. The default sampling rate for portable mode (button operation) is 312 Hz. This downloads at a rapid pace of 1 sec / 1 min of data.
