### ISSUE TITLE
Battor should report real timestamps, not starting from 0

### ISSUE THREAD

**Issue by peastham** [aschulm/battor#33]
It's pretty painful to manually record when I start the run, then later align the data to wall time / other logs -- requires post-processing scripts, usually several attempts to get the alignment right, etc.

Suggestion: a command-line option that can be sent along with '-b', that pushes the host's current time to the battor, then the timestamps start from that time. 

Or, always push the host timestamp, then it could be an option to the download command to apply the offset.  Might be nice to have that timestamp handy all the time in case there is confusion about where your data came from.

**Comment by aschulm** [comment]
Added in #52.
