### ISSUE TITLE
Slight mods needed to get it to work with OS X El Capitan

### ISSUE THREAD

**Issue by peastham** [aschulm/battor#35]
Using the built-in AppleUSBFTDI driver, I had to modify the tty name in battor.c to "/dev/cu.usbserial-482351150012". 

Not sure what that number is, and I don't see a better auto-symlink to use.

Other than that, it seems to be working fine!

macos 10.11.1

**Comment by aschulm** [comment]
Fixed in 3ece064645cab4302d866b1ab974755056c0a9f1. You can now pass the TTY path as a command line argument.
